### ISSUE TITLE
Powermenured.sh ?

### ISSUE THREAD

**Issue by rmelendezz** [Alopes01/Aesthetic-Polybar#1]
Hi,
 Great work again, I like the theming a lot, but I was unable to find the powermenure.sh script anywhere in your repos? can you share that as well?

Thanks

**Comment by Alopes01** [comment]
Thanks for the support, if you read  the readme with a little more attention you would notice that this repo only contains polybar themes, however I mentioned a rofi repo where there is powermemus and several more applets. Just look in the this repo does not have topic.
